language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: iSouH63UxCO4/M9ECLU5tF/tHiz/nF8O+lhloLvQsI4rj0eY0nuFkMo3K8vDR6Odt39lQbORGAmflptdZKWqrczKqKigCHgPFmlZXXxe2ONwntZLfcmcTQIa4lmvVMZUXB/i7RuAYKCIJktxVHOpnC/XEmEXq8K9jn89dYYB2L4=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: NvDD8n03Mp3T1+MpSLGNBmPNDUjrLGTfOqktp3h7lYK4dmYSOFkE2iXTCh4DlHXeHDK59sIGEKWiYPfbnzSCU4YmhNeNfTEB32ZBmYvst+HXw7jAT/D5KGZk5Sz7GCSg04gMXofDT+d3Nx5mleq94MPSKLfXKElKbuQ54oSHuZ0=
sudo: false
